# Generated by Django 5.1 on 2024-09-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personajes',
            name='Imagen',
            field=models.ImageField(null=True, upload_to='Personajes'),
        ),
    ]
