# Generated by Django 5.1 on 2024-09-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_personajes_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personajes',
            name='Nombre',
            field=models.TextField(max_length=30),
        ),
    ]
