# Generated by Django 5.1.1 on 2024-10-18 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_personajes_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenPersonajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imagen', models.ImageField(upload_to='Personajes')),
                ('Codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Imagenes', to='App.personajes')),
            ],
        ),
    ]
